config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  devise_for :users,
    controllers: {
      sessions: 'sessions',
      registrations: 'registrations',
      passwords: 'passwords'
    },
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register'
    }

  post '/m/:token', to: 'messages#create', as: :external_message

  resources :subscriptions, only: [:index, :create, :update]
  resources :mailboxes do
    resources :messages, only: [:index, :create, :destroy]
    member do
      post 'clear_messages', to: 'mailboxes#clear_messages'
    end
  end

  post 'auth' => 'user_token#create'
  namespace :admin do
    resources :users
    get 'dashboard', to: "dashboard#index", as: :dashboard
    get 'fetch_data', to: "dashboard#fetch_data"
  end

  namespace :api, defaults: { format: :json } do
    resources :mailboxes, only: [:index, :show]
  end

  # post '/checkout', to: 'payment#checkout'
  get '/execute', to: 'payment#execute'
  get 'pages/index'
  get 'pages/help'
  get 'pages/terms'
  get 'thank_you', to: 'pages#thank_you'

  get '*path', to: 'application#e_404'
end

app/models/message.rb
class Message < ApplicationRecord
  paginates_per 50
  store_accessor :message_fields
  attr_accessor :comment
  after_create :notify

  belongs_to :mailbox, counter_cache: true
  validates_length_of :comment, :in => 0..1

  default_scope { order(created_at: :desc) }
  scope :today, -> { where(created_at: (Time.zone.now.beginning_of_day..Time.zone.now)) }
  scope :week, -> { where(created_at: (Time.zone.now.beginning_of_week..Time.zone.now)) }
  scope :month, -> { where(created_at: (Time.zone.now.beginning_of_month..Time.zone.now)) }


  def self.search(q)
    if !q.blank?
      k, v = key_val_of(q)
      st = "message_fields ->> '%{key}' LIKE ?" % {key: k}
      where(st, "%#{v}%")
    else
      all
    end
  end

  def self.to_csv
    CSV.generate do |csv|
      limit(1000).each do |msg|
        csv << [msg.mailbox.name] + msg.attributes["message_fields"]
        .values_at(*msg.mailbox.allowed_fields.gsub(" ", "")
        .split(","))
      end
    end
  end

  private
    # "email: ww@ww.com" => ["email", "ww@ww.com"]
    def self.key_val_of(st)
      pattern = /([a-z]\w+\:)/
      value = st.sub(pattern, "").sub(":", "").strip
      key = st.remove(value).sub(":", "").strip

      [key, value]
    end

    def notify
      MailerJob.perform_async(self) if mailbox.should_reply
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!, except: :create
  before_action :set_message, only: [:destroy]
  skip_before_action :verify_authenticity_token, only: [:create]
  before_action :set_mailbox
  load_and_authorize_resource :mailbox
  load_and_authorize_resource through: :mailbox
  # skip_authorize_resource only: :create
  skip_authorize_resource :mailbox, only: :create
  layout 'mailbox_layout', only: [:index]

  def index
    @messages = @mailbox.messages
    @messages = @messages.today if params[:range] == 'today'
    @messages = @messages.week if params[:range] == 'week'
    @messages = @messages.search(params[:q]) if params[:q]

    @messages = Kaminari.paginate_array(@messages).page(params[:page])#.per(30)
    respond_to do |format|
      format.html
      format.json { render json: @mailbox }
      format.csv { send_data @mailbox.messages.to_csv }
    end

  end

  def create
    respond_to do |format|
      fields = @mailbox.allowed_fields.gsub(" ", "").split(",")
      h = {}
      fields.each { |f| h[f] = params[f] }
      attrs = message_params.tap { |p| p["message_fields"] = h }


      if @mailbox.messages.create(attrs)
        format.html { redirect_to mailbox_redirect(@mailbox) }
        format.json { render json: @mailbox }
      else
        format.html { redirect_to mailbox_redirect(@mailbox) }
        format.json { render json: @mailbox }
      end
    end
  end

  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to mailbox_messages_url(@mailbox) }
      format.json { head :no_content }
    end
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def set_mailbox
      by = params[:token] || params[:mailbox_id]
      @mailbox = Mailbox.find_by(token: by)
      redirect_to root_path unless @mailbox
    end

    def mailbox_redirect(mailbox)
      mailbox.site_url.blank? ? thank_you_path : url_link(@mailbox.site_url)
    end

    def message_params
      params.permit(:comment, message_fields: {})
    end
end

app/helpers/messages_helper.rb
module MessagesHelper

  def active_scope_link(scope)

  end

  def is_new(message)
    if message.created_at.between?((DateTime.now - 24.hours), DateTime.now)
      content_tag :span, "received today", class: "tag is-theme"
    end
  end

  def structured_fields_for(message)
    # h = {}
    # message.message_fields.each do |k, v|
    #   h[k]=v
    # end

    # content_tag :div, message.message_fields
    allowed_fields = message.mailbox.allowed_fields.gsub(" ", "").split(",")
    content_tag :ul, class: "message-fields" do
      allowed_fields.each do |f|
        concat content_tag :li, "#{f}: #{message.message_fields[f]}"
      end
    end
  end
end

app/views/messages/_form.html.erb
<%= form_with(model: [@mailbox, Message.new],
              url: external_message_path(@mailbox.token, Message.new)) do |form| %>


  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :message_email %>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject, id: :message_subject %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :message_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<article class="media message-item">

  <figure class="media-left">
    <p class="image is-48x48">
      <%= gravatar_image_tag(message.message_fields["email"])%>
    </p>
  </figure>

  <div class="media-content">
    <div class="content">
      <p>
        <small><%= link_to message.message_fields["email"], "mailto: #{message.message_fields["email"]}"%></small>
        <small><%= message.created_at %></small>
        <%= is_new(message) %>
        <br>
        <%= structured_fields_for(message) %>
      </p>
    </div>
  </div>
  <div class="media-right">
    <%= link_to "", mailbox_message_path(@mailbox, message), method: :delete, data: { confirm: 'Are you sure?' }, class: "delete" %>
  </div>
</article>

app/views/messages/index.html.erb
<nav class="level">
  <!-- Left side -->
  <div class="level-left">
    <div class="level-item">
      <p class="subtitle is-5">
        <strong><%= @messages.size %></strong> <%= "message".pluralize(@messages.size) %>
      </p>
    </div>
    <div class="level-item">
      <%= form_tag(mailbox_messages_path(@mailbox), method: :get) do %>
      <div class="field has-addons">
          <p class="control is-expanded">
            <%= text_field_tag :q, params[:q], placeholder: "key: search term", class: "input" %>
          </p>
          <p class="control">
          <%= submit_tag 'Search', name: nil, class: "button" %>
          </p>
      </div>
      <% end %>
    </div>
  </div>

  <!-- Right side -->
  <div class="level-right">
    <p class="level-item" id="toggle-view"><a class="button is-small" href="#">Toggle view</a></p>
    <p class="level-item"><%= link_to "All", mailbox_messages_path() %></p>
    <p class="level-item"><%= link_to "Day", mailbox_messages_path(range: 'today') %></p>
    <p class="level-item"><%= link_to "Week", mailbox_messages_path(range: 'week') %></p>
    <p class="level-item"><%= link_to "Month", mailbox_messages_path(range: 'month') %></p>
  </div>
</nav>

<div class="messages">
  <% if @messages.any? %>
    <%= render @messages %>
  <% else %>
    <p class="no-messages has-text-centered">no messages</p>
  <% end %>
</div>

<%= paginate @messages %>