config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  devise_for :users,
    controllers: {
      sessions: 'sessions',
      registrations: 'registrations',
      passwords: 'passwords'
    },
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register'
    }

  post '/m/:token', to: 'messages#create', as: :external_message

  resources :subscriptions, only: [:index, :create, :update]
  resources :mailboxes do
    resources :messages, only: [:index, :create, :destroy]
    member do
      post 'clear_messages', to: 'mailboxes#clear_messages'
    end
  end

  post 'auth' => 'user_token#create'
  namespace :admin do
    resources :users
    get 'dashboard', to: "dashboard#index", as: :dashboard
    get 'fetch_data', to: "dashboard#fetch_data"
  end

  namespace :api, defaults: { format: :json } do
    resources :mailboxes, only: [:index, :show]
  end

  # post '/checkout', to: 'payment#checkout'
  get '/execute', to: 'payment#execute'
  get 'pages/index'
  get 'pages/help'
  get 'pages/terms'
  get 'thank_you', to: 'pages#thank_you'

  get '*path', to: 'application#e_404'
end

app/models/mailbox.rb
class Mailbox < ApplicationRecord
  before_validation :generate_mailbox_token, on: :create
  has_many :messages, dependent: :destroy
  belongs_to :user, counter_cache: true
  validates :name, presence: true, uniqueness: { scope: :user_id }
  # validates :site_url, presence: true
  validate :validate_allowed_fields_amount
  validate :validate_mailbox_limit, on: :create
  validates :reply_body, presence: true, if: :should_reply?

  def to_param
    token
  end

  private
    def generate_mailbox_token
      self.token = SecureRandom.hex[0..15] # Digest::SHA1.hexdigest([Time.now, rand].join)[0..15]
      generate_mailbox_token if Mailbox.exists?(token: self.token)
    end

    def validate_allowed_fields_amount
      fields = allowed_fields.gsub(" ", "").split(",")
      if fields.length > 10
        errors.add(:allowed_fields, "max 10 fields")
      elsif fields.length < 1
        errors.add(:allowed_fields, "min 1 field")
      end
    end

    def should_reply?
      should_reply == true
    end

    def validate_mailbox_limit
      if user.mailboxes.length == user.plan.n_mailboxes
        errors.add(:number_of_mailboxes, "limit reached")
      end
    end

end

app/controllers/api/mailboxes_controller.rb
class Api::MailboxesController < Api::BaseController
  before_action :set_mailbox, only: [:show]
  def index
    @mailboxes = current_user.mailboxes
    render 'api/mailboxes/index.json.jbuilder'
  end

  def show
    render 'api/mailboxes/show.json.jbuilder'
  end


  private
  def set_mailbox
    @mailbox = current_user.mailboxes.find_by(token: params[:id])
    render {} unless @mailbox
  end
end

app/controllers/mailboxes_controller.rb
class MailboxesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_mailbox, only: [:show, :edit, :update, :destroy, :clear_messages]
  layout 'mailbox_layout', only: [:show, :edit]
  load_and_authorize_resource

  def index
    @mailboxes = current_user.mailboxes

    @today = current_user.messages.today.size
    @week = current_user.messages.week.size
    @month = current_user.messages.month.size
    @all_time = current_user.messages.size
  end

  def show
  end

  def new
    @mailbox = Mailbox.new
  end

  def edit
  end

  def create
    @mailbox = current_user.mailboxes.build(mailbox_params)
      respond_to do |format|
        if @mailbox.save
          format.html { redirect_to @mailbox, notice: 'Mailbox was successfully created.' }
          format.json { render :show, status: :created, location: @mailbox }
        else
          format.html { render :new }
          format.json { render json: @mailbox.errors, status: :unprocessable_entity }
        end
      end
  end

  def update
    respond_to do |format|
      if @mailbox.update(mailbox_params)
        format.html { redirect_to @mailbox, notice: 'Mailbox was successfully updated.' }
        format.json { render :show, status: :ok, location: @mailbox }
      else
        format.html { render :edit }
        format.json { render json: @mailbox.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @mailbox.destroy
    respond_to do |format|
      format.html { redirect_to mailboxes_url, notice: 'Mailbox was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def clear_messages
    messages = @mailbox.messages
    messages.destroy_all unless messages.nil?
    redirect_to @mailbox, notice: 'Messages were successfully deleted.'
  end

  private
    def set_mailbox
      @mailbox = current_user.mailboxes.find_by(token: params[:id])
    end

    def mailbox_params
      params.require(:mailbox).permit(:token, :site_url, :name, :note, :allowed_fields, :should_reply, :reply_body)
    end
end

app/helpers/mailboxes_helper.rb
module MailboxesHelper

  def form_code(token, fields)
    action_url = "#{root_url}m/#{token}"
    inputs = %Q()
    fields = fields.gsub(" ", "").split(",")
    fields.each do |f|
      field = %Q(
        <div class="field">
          <label for="#{f}">#{f}</label>
          <input type="text" name="#{f}">
        </div>
      )
      inputs += field
    end

    form = %Q(
      <form action="#{action_url}" accept-charset="UTF-8" method="post">
        <input name="utf8" type="hidden" value="✓">
        #{inputs}
        <!-- keep this -->
        <div style="width: 1px; height: 1px; overflow: hidden; display: none;">
          Please leave following field blank:
          <textarea name="comment"></textarea>
        </div>
        <!-- keep this -->

        <div class="actions">
          <input type="submit" value="Send">
        </div>
      </form>
    )

    form.strip.gsub(" ", "").gsub("\n", "")
    markdown(form.to_s)
  end

  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
    extensions = {

    })
    raw(markdown.render(text))
  end
end

app/views/mailboxes/_form.html.erb
<%= simple_form_for(@mailbox) do |form| %>
  <% if @mailbox.errors.any? %>
    <div id="error_explanation" class="notification is-danger">
      <button class="delete"></button>
      <h2><%= pluralize(@mailbox.errors.count, "error") %> prohibited this mailbox from being saved:</h2>

      <ul>
      <% @mailbox.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "label" %>
    <div class="control">
      <%= form.input_field :name, id: :mailbox_name, class: "input", placeholder: "My blog contact form" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :site_url, "Allowed fields", class: "label" %>
    <div class="control">
      <%= form.input_field :allowed_fields, value: @mailbox.allowed_fields, id: :mailbox_allowed_fields, class: "input", placeholder: "email, phone, body" %>
    </div>
  </div>

  <% if @mailbox.messages.any? %>
  <article class="message is-info">
    <div class="message-body">
      Looks like you already have some messages in your mailbox, please delete them before editing allowed fields.
    </div>
  </article>
  <% end %>

  <div class="field">
    <%= form.label :site_url, "Redirect URL", class: "label" %>
    <div class="control">
      <%= form.input_field :site_url, id: :mailbox_site_url, class: "input", placeholder: "formiqo.com/thank_you" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :note, class: "label" %>
    <div class="control">
      <%= form.input_field :note, id: :mailbox_note, class: "textarea", placeholder: "Any note that you might need for this mailbox." %>
    </div>
  </div>


  <div class="field">
    <div class="control">
      <label class="checkbox">
      <%= form.input_field :should_reply, as: :boolean, checked_value: true, unchecked_value: false %>
      Reply to submitter
      </label>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= form.input_field :reply_body, class: "textarea", placeholder: "Reply with this text. You're not restricted but keep it short.", disabled: true %>
    </div>
  </div>


  <div class="field is-grouped">
    <p class="control">
      <%= form.submit "Save changes", class: "button is-primary" %>
    </p>
    <p class="control">
      <%= link_to 'Cancel', :back, class: "button" %>
    </p>
  </div>
<% end %>

app/views/mailboxes/edit.html.erb
<%= render 'form', mailbox: @mailbox %>

app/views/mailboxes/index.html.erb
<nav class="level">
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Today</p>
      <p class="title"><%= @today %></p>
    </div>
  </div>
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Week</p>
      <p class="title"><%= @week %></p>
    </div>
  </div>
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Month</p>
      <p class="title"><%= @month %></p>
    </div>
  </div>
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">All time</p>
      <p class="title"><%= @all_time %></p>
    </div>
  </div>
</nav>

app/views/mailboxes/new.html.erb
<h1 class="title">New Mailbox</h1>

<%= render 'form', mailbox: @mailbox %>

app/views/mailboxes/show.html.erb
<div class="columns">
  <div class="column">
    <p>
      <strong>Name:</strong>
      <%= @mailbox.name %>
    </p>

    <p>
      <strong>Allowed fields:</strong>
      <%= @mailbox.allowed_fields %>
    </p>

    <p>
      <strong>Redirect URL:</strong>
      <%= link_to @mailbox.site_url, url_link(@mailbox.site_url), target: '_blank' %>
    </p>

    <p>
      <strong>Reply to submitter:</strong>
      <%= @mailbox.should_reply ? "yes" : "no" %>
    </p>

    <p>
      <strong>Note:</strong>
      <%= @mailbox.note %>
    </p>
  </div>
</div>

<div class="field is-grouped">
  <p class="control">
    <%= link_to "Delete this mailbox", @mailbox, method: :delete,
      class: "button is-small is-outlined",
      data: { confirm: "The mailbox and all its messages will be deleted. Are you sure?" } %>
  </p>
  <p class="control">
    <%= link_to "Clear all messages", clear_messages_mailbox_path(@mailbox),
      method: :post, class: "button is-small is-outlined",
      data: { confirm: "All messages of this mailbox will be deleted. Are you sure?" } %>
  </p>
</div>

<hr>

<div class="columns">
  <div class="column">
    <p>
      <article class="message is-info">
        <div class="message-body">
          Here's your form code. Update it where necessary but keep the first 2 lines and the hidden div to prevent spam.
        </div>
      </article>

      <figure class="highlight">
        <%= form_code(@mailbox.token, @mailbox.allowed_fields) %>
      </figure>
    </p>
  </div>
</div>