config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  devise_for :users,
    controllers: {
      sessions: 'sessions',
      registrations: 'registrations',
      passwords: 'passwords'
    },
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register'
    }

  post '/m/:token', to: 'messages#create', as: :external_message

  resources :subscriptions, only: [:index, :create, :update]
  resources :mailboxes do
    resources :messages, only: [:index, :create, :destroy]
    member do
      post 'clear_messages', to: 'mailboxes#clear_messages'
    end
  end

  post 'auth' => 'user_token#create'
  namespace :admin do
    resources :users
    get 'dashboard', to: "dashboard#index", as: :dashboard
    get 'fetch_data', to: "dashboard#fetch_data"
  end

  namespace :api, defaults: { format: :json } do
    resources :mailboxes, only: [:index, :show]
  end

  # post '/checkout', to: 'payment#checkout'
  get '/execute', to: 'payment#execute'
  get 'pages/index'
  get 'pages/help'
  get 'pages/terms'
  get 'thank_you', to: 'pages#thank_you'

  get '*path', to: 'application#e_404'
end

app/models/user.rb
class User < ApplicationRecord
  after_create :add_subscription
  after_create :add_mailbox

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  alias_method :authenticate, :valid_password?

  has_many :mailboxes, dependent: :destroy
  has_many :messages, through: :mailboxes
  has_one :subscription, dependent: :destroy
  has_one :plan, through: :subscription

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates_format_of :email, :with => EMAIL_REGEX

  def remember_me
    true
  end

  # def reached_mailbox_limit?
  #   mailboxes.length > subscription.plan.n_mailboxes
  # end

  private
    def add_subscription
      Subscription.create(plan_id: 1, user_id: id, end_date: Time.zone.now + 3.day)
    end

    def add_mailbox
      Mailbox.create(user_id: id,
          name: "Demo mailbox",
          site_url: "",
          note: "Contact form for my blog", allowed_fields: "email, subject, body")
    end

    def self.from_token_payload payload
      self.find payload["sub"]
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminBase
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    # add search
    if params[:q] && !params[:q].empty?
      @users = User.where('email LIKE ?', params[:q]).page(params[:page]).per(50)
    else
      @users = User.all.page(params[:page]).per(50)
    end


  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
    #code
  end

  def create
    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    if params[:user][:password].blank?
      @user.update_without_password(user_params)
    else
      @user.update_attributes(user_params)
    end
    if @user.errors.blank?
      redirect_to admin_users_path, :notice => "User updated successfully."
    else
      render :edit
   end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :admin)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, user] do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="notification is-danger">
      <button class="delete"></button>
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this mailbox from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email, class: "label" %>
    <div class="control">
      <%= form.input_field :email, id: :user_name, class: "input", placeholder: "" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :password, class: "label" %>
    <div class="control">
      <%= form.input_field :password, id: :user_password, class: "input", placeholder: "" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <label class="checkbox">
      <%= form.input_field :admin, as: :boolean, checked_value: true, unchecked_value: false %>
      Is admin?
      </label>
    </div>
  </div>

  <div class="field is-grouped">
    <p class="control">
      <%= form.submit "Save", class: "button is-primary" %>
    </p>
    <p class="control">
      <%= link_to 'Cancel', admin_users_url, class: "button" %>
    </p>
  </div>

<% end %>

app/views/admin/users/edit.html.erb
<h1 class="title">Edit user</h1>

<div class="columns">
  <div class="column is-4">
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/admin/users/index.html.erb
<h1 class="title">Users</h1>
<div class="columns">
  <div class="column">
    <%= link_to new_admin_user_path, { class: "button is-primary" } do %>
      <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;Add user
    <% end %>
  </div>
</div>

<div class="columns">
  <div class="column">
    <div class="level-left">
      <div class="level-item">
        <%= form_tag(admin_users_path, method: :get) do %>
        <div class="field has-addons">
            <p class="control is-expanded">
              <%= text_field_tag :q, params[:q], placeholder: "user email", class: "input" %>
            </p>
            <p class="control">
            <%= submit_tag 'Search', name: nil, class: "button" %>
            </p>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<table class="table is-fullwidth">
  <thead>
    <tr>
      <th>id</th>
      <th>email</th>
      <th>created</th>
      <th>subscription</th>
      <th>N Mailboxes</th>
      <th>admin</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= link_to "#{user.email}", admin_user_path(user) %></td>
      <td><%= user.created_at %></td>
      <td><%= subscription_status(user) %></td>
      <td><%= user.mailboxes.size %></td>
      <td>
        <!-- too lazy fo a helper -->
        <% if user.admin %>
          <span class="tag is-dark"><%= user.admin ? 'Y' : 'N' %></span>
        <% else %>
          <%= user.admin ? 'Y' : 'N'  %>
        <% end %>
      </td>
      <td>
        <%= link_to "Edit", edit_admin_user_path(user), class: "button is-small is-primary" %>
        <%= link_to "Delete", admin_user_path(user), method: :delete, data: { confirm: "Are you sure?" }, class: "button is-small is-danger"%>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

app/views/admin/users/new.html.erb
<h1 class="title">New user</h1>

<div class="columns">
  <div class="column is-4">
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="columns">
  <div class="column">
    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Is admin:</strong>
      <%= @user.admin ? 'Y' : 'N' %>
    </p>

    <p>
      <strong>Subscription ends:</strong>
      <%= subscription_status(@user) %> /
      <%= @user.subscription.end_date %>
    </p>

    <p>
      <strong>Mailboxes:</strong>
      <%= @user.mailboxes_count %> out of <%= @user.plan.n_mailboxes %>
    </p>

  </div>
</div>