config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  devise_for :users,
    controllers: {
      sessions: 'sessions',
      registrations: 'registrations',
      passwords: 'passwords'
    },
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register'
    }

  post '/m/:token', to: 'messages#create', as: :external_message

  resources :subscriptions, only: [:index, :create, :update]
  resources :mailboxes do
    resources :messages, only: [:index, :create, :destroy]
    member do
      post 'clear_messages', to: 'mailboxes#clear_messages'
    end
  end

  post 'auth' => 'user_token#create'
  namespace :admin do
    resources :users
    get 'dashboard', to: "dashboard#index", as: :dashboard
    get 'fetch_data', to: "dashboard#fetch_data"
  end

  namespace :api, defaults: { format: :json } do
    resources :mailboxes, only: [:index, :show]
  end

  # post '/checkout', to: 'payment#checkout'
  get '/execute', to: 'payment#execute'
  get 'pages/index'
  get 'pages/help'
  get 'pages/terms'
  get 'thank_you', to: 'pages#thank_you'

  get '*path', to: 'application#e_404'
end

app/views/layouts/_alerts.html.erb
<% flash.each do |k, v| %>
  <% if k == "notice" || "info" %>
    <%= content_tag :div, class: "notification is-info" do %>
      <%= button_tag "", class: "delete" %>
      <%= v %>
    <% end %>
  <% elsif k == "error" %>
    <%= content_tag :div, class: "notification is-danger" do %>
      <%= button_tag "", class: "delete" %>
      <%= v %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_app_icon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="\favicon/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="\favicon/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="\favicon/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="\favicon/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="\favicon/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="\favicon/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="\favicon/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="\favicon/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="\favicon/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="\favicon/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="\favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="\favicon/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="\favicon/favicon-16x16.png">
<link rel="manifest" href="\favicon/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="\favicon/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_menu.html.erb
<aside class="menu">
  <%= subscription_expiration(current_user) %>
  <div class="block">
    <%= link_to new_mailbox_path, { class: "button is-primary is-fullwidth" } do %>
      <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;New mailbox
    <% end %>
  </div>
  <p class="menu-label">
    Mailboxes
  </p>
  <ul class="menu-list">
    <% current_user.mailboxes.each do |mb| %>
      <% if mb.persisted? %>
        <li>
          <%= link_to mailbox_path(mb), {class: "#{'is-active' if @mailbox.try(:name) == mb.name }"}  do %>
            <%= mb.name %>
          <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>
</aside>

app/views/layouts/_nav.html.erb
<nav class="navbar ">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <img src="<%= image_path('logo.png') %>" alt="formiqo" width="112" height="28">
    </a>

    <div class="navbar-burger burger" data-target="navMenuExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navMenuExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Home", mailboxes_path, class: "navbar-item" %>
      <div class="navbar-item has-dropdown is-hoverable">
        <div class="navbar-link">
          More
        </div>
        <div id="moreDropdown" class="navbar-dropdown ">

          <%= link_to pages_help_path, class: "navbar-item", id: "link-to-pay" do %>
            <div class="level is-mobile">
              <div class="level-left">
                <div class="level-item">
                  <p>
                    <strong>Help</strong>
                    <br>
                    <small>Overview of some aspects</small>
                  </p>
                </div>
              </div>
            </div>
          <% end %>
          <%= link_to subscriptions_path, class: "navbar-item", id: "link-to-pay" do %>
          <div class="level is-mobile">
            <div class="level-left">
              <div class="level-item">
                <p>
                  <strong>Subscription Settings</strong>
                </p>
              </div>
            </div>
          </div>
          <% end %>
          <%= link_to edit_user_registration_path, class: "navbar-item" do %>
          <div class="level is-mobile">
            <div class="level-left">
              <div class="level-item">
                <p>
                  <strong>Account Settings</strong>
                  <br>
                  <small></small>
                </p>
              </div>
            </div>
          </div>
          <% end %>

          <% if user_signed_in? %>
            <%= link_to destroy_user_session_path, method: :delete, class: "navbar-item" do %>
            <div class="level is-mobile">
              <div class="level-left">
                <div class="level-item">
                  <p>
                    <strong>Sign out</strong>
                    <br>
                    <small></small>
                  </p>
                </div>
              </div>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <% if user_signed_in? %>
    <% if can? :manage, :all %>
      <div class="navbar-end">
        <%= link_to admin_dashboard_url, class: "navbar-item" do%>
          <i class="fa fa-bar-chart" aria-hidden="true"></i>
        <% end %>
      </div>
    <% end %>
    <% end %>


  </div>
</nav>

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Formiqo</title>
    <%= csrf_meta_tags %>
    <%= render "layouts/app_icon" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'dash' %>
  </head>

  <body>
    <div class="container is-fluid">
      <div class="columns">
        <div class="column">
          <%= render "layouts/nav" %>
        </div>
      </div>
    </div>

    <div class="section">
      <div class="container is-fluid">
        <div class="columns">
          <div class="column">
            <div class="tabs is-small">
              <ul>
                <li><%= link_to "Dashboard", admin_dashboard_path %></li>
                <li><%= link_to "Users", admin_users_path %></li>
              </ul>
            </div>

            <%= yield %>
          </div>
        </div>
      </div>
    </div>


  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Formiqo</title>
    <%= csrf_meta_tags %>
    <%= render "layouts/app_icon" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container is-fluid">
      <div class="columns">
        <div class="column">
          <%= render "layouts/nav" %>
        </div>
      </div>
    </div>

    <div class="section">
      <div class="container is-fluid">
        <div class="columns">
          <div class="column is-2">
            <%= render "layouts/menu"%>
          </div>
          <div class="column">
            <%= render 'layouts/alerts' %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/layouts/auth_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Formiqo</title>
    <%= csrf_meta_tags %>
    <%= render "layouts/app_icon" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <section class="hero is-fullheight is-90vh is-default is-bold">
      <div class="hero-head">
        <div class="container is-fluid">
          <nav class="navbar ">
            <div class="navbar-brand">
              <a class="navbar-item" href="/">
                <img src="<%= image_path('logo.png') %>" alt="formiqo" width="112" height="28">
              </a>

              <div class="navbar-burger burger" data-target="navMenuExample">
                <span></span>
                <span></span>
                <span></span>
              </div>
            </div>

            <div id="navMenuExample" class="navbar-menu">

              <div class="navbar-end">
                <%= link_to "Help", pages_help_path, class: "navbar-item is-hidden-desktop-only" %>

                <div class="navbar-item">
                  <div class="field is-grouped">
                    <p class="control">
                      <%= link_to new_user_session_path, class: "button" do %>
                      <span>
                        Log In
                      </span>
                      <% end %>
                    </p>
                    <p class="control">
                      <%= link_to new_user_registration_path, class: "button is-primary" do %>
                        <span>Sign Up</span>
                      <% end %>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </div>

        <div class="hero-body">
          <div class="container is-fluid">

            <div class="columns is-vcentered">
              <div class="column is-4 is-offset-4">
                <%= render 'layouts/alerts' %>
                <%= yield %>
              </div>
            </div>
          </div>
        </div>

      </section>

  </body>
</html>

app/views/layouts/mailbox_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Formiqo</title>
    <%= csrf_meta_tags %>
    <%= render "layouts/app_icon" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container is-fluid">
      <div class="columns">
        <div class="column">
          <%= render "layouts/nav" %>
        </div>
      </div>
    </div>

    <div class="section">
      <div class="container is-fluid">
        <div class="columns">
          <div class="column is-2">
            <%= render "layouts/menu" %>
          </div>
          <div class="column">

            <div class="tabs is-toggle">
              <ul>
                <li class="<%= 'is-active' if current_page?(mailbox_path(@mailbox)) %>">
                  <%= link_to mailbox_path(@mailbox) do %>
                    <span class="icon is-small"><i class="fa fa-info"></i></span>
                    <span>Setup</span>
                  <% end %>
                </li>
                <li class="<%= 'is-active' if current_page?(mailbox_messages_path(@mailbox)) %>">
                  <%= link_to mailbox_messages_path(@mailbox) do %>
                    <span class="icon is-small"><i class="fa fa-envelope-o"></i></span>
                    <span>Messages</span>
                  <% end %>
                </li>
                <li class="<%= 'is-active' if current_page?(edit_mailbox_path(@mailbox)) %>">
                  <%= link_to edit_mailbox_path(@mailbox) do %>
                    <span class="icon is-small"><i class="fa fa-sliders"></i></span>
                    <span>Edit</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to mailbox_messages_path(@mailbox, format: :csv) do %>
                    <span class="icon is-small"><i class="fa fa-table"></i></span>
                    <span>Export to CSV</span>
                  <% end %>
                </li>
              </ul>
            </div>

            <%= yield %>
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/layouts/pages_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Formiqo</title>
    <%= csrf_meta_tags %>
    <%= render "layouts/app_icon" %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Effortless forms solution for your static sites.">
    <meta name="keywords" content="form, forms, jekyll, hugo, middleman, static, contact, contact form">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="hero is-fullheight is-default is-bold">
      <div class="hero-head">
        <div class="container is-fluid">
          <% if user_signed_in? %>
            <%= render "layouts/nav" %>
          <% else %>
          <nav class="navbar ">
            <div class="navbar-brand">
              <a class="navbar-item" href="/">
                <img src="<%= image_path('logo.png') %>" alt="formiqo" width="112" height="28">
              </a>

              <div class="navbar-burger burger" data-target="navMenuExample">
                <span></span>
                <span></span>
                <span></span>
              </div>
            </div>

            <div id="navMenuExample" class="navbar-menu">

              <div class="navbar-end">
                <%= link_to "Help", pages_help_path, class: "navbar-item is-hidden-desktop-only" %>

                <div class="navbar-item">
                  <div class="field is-grouped">
                    <p class="control">
                      <%= link_to new_user_session_path, class: "button" do %>
                      <span>
                        Log In
                      </span>
                      <% end %>
                    </p>
                    <p class="control">
                      <%= link_to new_user_registration_path, class: "button is-primary" do %>
                        <span>Sign Up</span>
                      <% end %>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </nav>
          <% end %>


        </div>
      </div>
        <%= yield %>
    </section>

    <footer class="footer">
      <div class="container">
        <div class="content has-text-centered">
          <p>
            <a href="/">&copy; formiqo</a> /
            <%= link_to "Terms", pages_terms_path %> /
            <a href="mailto: support@formiqo.com">Contact</a>
          </p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/redirect.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Formiqo</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="hero is-fullheight is-bold">
      <%= yield %>
    </section>
  </body>
</html>